using Information.Enums;

namespace Information;

public record ResourceTypeInfo
{
	//public record Entry
	//{
	//	public required ResourceType Id { get; init; }
	//	public required string Name { get; init; }
	//}

	public static Dictionary<ResourceType, string> Info { get; } = new()
	{
		{ ResourceType.Texture, "Texture" },
		{ ResourceType.Material, "Material" },
		{ ResourceType.RenderableMesh, "Renderable Mesh" },
		{ ResourceType.TextFile, "Text File" },
		{ ResourceType.DrawIndexParams, "Draw Indexed Parameters" },
		{ ResourceType.IndexBuffer, "Index Buffer" },
		{ ResourceType.MeshState, "Mesh State" },
		{ ResourceType.TEXTUREAUXINFO, "Auxiliary Texture Info" },
		{ ResourceType.VERTEXBUFFERITEM, "Vertex Buffer Item" },
		{ ResourceType.VertexBuffer, "Vertex Buffer" },
		{ ResourceType.VertexDescriptor, "Vertex Descriptor" },
		{ ResourceType.RwMaterialCRC32, "Material CRC32" },
		{ ResourceType.Renderable, "Renderable" },
		{ ResourceType.MaterialTechnique, "Material Technique" },
		{ ResourceType.TextureState, "Texture State" },
		{ ResourceType.MaterialState, "Material State" },
		{ ResourceType.DepthStencilState, "Depth Stencil State" },
		{ ResourceType.RasterizerState, "Rasterizer State" },
		{ ResourceType.RwShaderProgramBuffer, "Shader Program Buffer" },
		{ ResourceType.RenderTargetState, "Render Target State" },
		{ ResourceType.RwShaderParameter, "Shader Parameter" },
		{ ResourceType.RenderableAssembly, "Renderable Assembly" },
		{ ResourceType.RwDebug, "Debug" },
		{ ResourceType.KdTree, "K-Dimensional Tree" },
		{ ResourceType.VoiceHierarchy, "Voice Hierarchy" },
		{ ResourceType.Snr, "SNR" },
		{ ResourceType.InterpreterData, "Interpreter Data" },
		{ ResourceType.AttribSysSchema, "AttribSys Schema" },
		{ ResourceType.AttribSysVault, "AttribSys Vault" },
		{ ResourceType.EntryList, "Entry List" },
		{ ResourceType.AptData, "Apt Data" },
		{ ResourceType.GuiPopup, "GUI Popup" },
		{ ResourceType.Unknown_0x20, "Unknown (type ID 0x20)" },
		{ ResourceType.Font, "Font" },
		{ ResourceType.LuaCode, "Lua Code" },
		{ ResourceType.InstanceList, "Instance List" },
		{ ResourceType.ClusteredMesh, "Clustered Mesh" },
		{ ResourceType.IdList, "ID List" },
		{ ResourceType.InstanceCollisionList, "Instance Collision List" },
		{ ResourceType.Language, "Language" },
		{ ResourceType.SatNavTile, "Satnav Tile" },
		{ ResourceType.SatNavTileDirectory, "Satnav Tile Directory" },
		{ ResourceType.Model, "Model" },
		{ ResourceType.ColourCube, "Colour Cube" },
		{ ResourceType.HudMessage, "HUD Message" },
		{ ResourceType.HudMessageList, "HUD Message List" },
		{ ResourceType.HudMessageSequence, "HUD Message Sequence" },
		{ ResourceType.HudMessageSequenceDictionary, "HUD Message Sequence Dictionary" },
		{ ResourceType.WorldPainter2D, "World Painter 2D" },
		{ ResourceType.PFXHookBundle, "PFX Hooks" },
		{ ResourceType.ShaderTechnique, "Shader Technique" },
		{ ResourceType.RawFile, "Raw Data" },
		{ ResourceType.ICETakeDictionary, "ICE Take Dictionary" },
		{ ResourceType.VideoData, "Video Data" },
		{ ResourceType.PolygonSoupList, "Polygon Soup List" },
		{ ResourceType.DeveloperList, "Developer List" },
		{ ResourceType.CommsToolListDefinition, "Comms Tool List Definition" },
		{ ResourceType.CommsToolList, "Comms Tool List" },
		{ ResourceType.BinaryFile, "Binary File" },
		{ ResourceType.AnimationCollection, "Animation Collection" },
		{ ResourceType.CharAnimBankFile, "Character Animation Bank Data" },
		{ ResourceType.WeaponFile, "Weapon Data" },
		{ ResourceType.VFXFile, "VFX Data" },
		{ ResourceType.BearFile, "Bear Data" },
		{ ResourceType.BkPropInstanceList, "Prop Instance List" },
		{ ResourceType.Registry, "Registry" },
		{ ResourceType.GENERIC_RWAC_FACTORY_CONFIGURATION, "Generic RWAC Factory Configuration" },
		{ ResourceType.GenericRwacWaveContent, "Generic RWAC Wave Content" },
		{ ResourceType.GinsuWaveContent, "Ginsu Wave Content" },
		{ ResourceType.AemsBank, "AEMS Bank" },
		{ ResourceType.Csis, "CSIS" },
		{ ResourceType.Nicotine, "Nicotine Map" },
		{ ResourceType.Splicer, "Splicer" },
		{ ResourceType.FreqContent, "Frequency Content" },
		{ ResourceType.VoiceHierarchyCollection, "Voice Hierarchy Collection" },
		{ ResourceType.GenericRwacReverbIRContent, "Generic RWAC Reverb IR Content" },
		{ ResourceType.SnapshotData, "Snapshot Data" },
		{ ResourceType.ZoneList, "Zone List" },
		{ ResourceType.Unknown_0xC000, "Unknown (type ID 0xC000)" },
		{ ResourceType.VFX, "VFX" },
		{ ResourceType.LoopModel, "Loop Model" },
		{ ResourceType.AISections, "AI Sections" },
		{ ResourceType.TrafficData, "Traffic Data" },
		{ ResourceType.TriggerData, "Trigger Data" },
		{ ResourceType.DeformationModel, "Deformation Model" },
		{ ResourceType.VehicleList, "Vehicle List" },
		{ ResourceType.GraphicsSpec, "Vehicle Graphics" },
		{ ResourceType.PhysicsSpec, "Vehicle Physics" },
		{ ResourceType.ParticleDescriptionCollection, "Particle Description Collection" },
		{ ResourceType.WheelList, "Wheel List" },
		{ ResourceType.WheelGraphicsSpec, "Wheel Graphics" },
		{ ResourceType.TextureNameMap, "Texture Name Map" },
		{ ResourceType.ICEList, "ICE List" },
		{ ResourceType.ICEData, "ICE Data" },
		{ ResourceType.ProgressionData, "Progression Data" },
		{ ResourceType.PropPhysics, "Prop Physics" },
		{ ResourceType.PropGraphicsList, "Prop Graphics List" },
		{ ResourceType.PropInstanceData, "Prop Instance Data" },
		{ ResourceType.EnvironmentKeyframe, "Environment Keyframe" },
		{ ResourceType.EnvironmentTimeLine, "Environment Timeline" },
		{ ResourceType.EnvironmentDictionary, "Environment Dictionary" },
		{ ResourceType.GraphicsStub, "Traffic Graphics Stub" },
		{ ResourceType.StaticSoundMap, "Static Sound Map" },
		{ ResourceType.DEPRECATED_PFXHookBundle, "PFX Hooks (deprecated)" },
		{ ResourceType.StreetData, "Street Data" },
		{ ResourceType.VFXMeshCollection, "VFX Mesh Collection" },
		{ ResourceType.MassiveLookupTable, "Massive Lookup Table" },
		{ ResourceType.VFXPropCollection, "VFX Prop Collection" },
		{ ResourceType.StreamedDeformationSpec, "Streamed Deformation" },
		{ ResourceType.ParticleDescription, "Particle Description" },
		{ ResourceType.PlayerCarColours, "Player Car Colours" },
		{ ResourceType.ChallengeList, "Challenge List" },
		{ ResourceType.FlaptFile, "Flapt File" },
		{ ResourceType.ProfileUpgrade, "Profile Upgrade" },
		{ ResourceType.OfflineChallengeList, "Offline Challenge List" },
		{ ResourceType.VehicleAnimation, "Vehicle Animation" },
		{ ResourceType.BodypartRemapData, "Body Part Remap Data" },
		{ ResourceType.LUAList, "Lua List" },
		{ ResourceType.LUAScript, "Lua Script" },
		{ ResourceType.BkSoundWeapon, "Weapon Sound Data" },
		{ ResourceType.BkSoundGunsu, "Gunsu" },
		{ ResourceType.BkSoundBulletImpact, "Bullet Impact Sound Data" },
		{ ResourceType.BkSoundBulletImpactList, "Bullet Impact List" },
		{ ResourceType.BkSoundBulletImpactStream, "Bullet Impact Stream" }
	};
}
