using Information.Enums;

namespace Information;

// Not related to BundleV2, but to TypeV2, introduced in BundleV2 version 3.
public record ResourceTypeV2Info
{
	public record Entry
	{
		public required ResourceTypeV2 Id { get; init; }
		public required string Name { get; init; }
	}

	public static Dictionary<ResourceTypeV2, string> Info { get; } = new()
	{
		{ ResourceTypeV2.Texture, "Texture" },
		{ ResourceTypeV2.Material, "Material" },
		{ ResourceTypeV2.VertexDescriptor, "Vertex Descriptor" },
		{ ResourceTypeV2.VertexProgramState, "Vertex Program State (RenderWare)" },
		{ ResourceTypeV2.Renderable, "Renderable" },
		{ ResourceTypeV2.MaterialState, "Material State" },
		{ ResourceTypeV2.SamplerState, "Sampler State" },
		{ ResourceTypeV2.ShaderProgramBuffer, "Shader Program Buffer (RenderWare)" },
		{ ResourceTypeV2.AttribSysSchema, "AttribSys Schema" },
		{ ResourceTypeV2.AttribSysVault, "AttribSys Vault" },
		{ ResourceTypeV2.GeneSysDefinition, "GeneSys Definition" },
		{ ResourceTypeV2.GeneSysInstance, "GeneSys Instance" },
		{ ResourceTypeV2.GenesysType, "Genesys Type" },
		{ ResourceTypeV2.GenesysObject, "Genesys Object" },
		{ ResourceTypeV2.BinaryFile, "Binary File" },
		{ ResourceTypeV2.MiiData, "Mii Data" },
		{ ResourceTypeV2.EntryList, "Entry List" },
		{ ResourceTypeV2.BundleIndex, "Bundle Index" },
		{ ResourceTypeV2.Font, "Font" },
		{ ResourceTypeV2.LuaCode, "Lua Code" },
		{ ResourceTypeV2.InstanceList, "Instance List" },
		{ ResourceTypeV2.Model, "Model" },
		{ ResourceTypeV2.ColourCube, "Colour Cube" },
		{ ResourceTypeV2.Shader, "Shader" },
		{ ResourceTypeV2.PolygonSoupList, "Polygon Soup List" },
		{ ResourceTypeV2.PolygonSoupTree, "Polygon Soup Tree" },
		{ ResourceTypeV2.IdList, "ID List" },
		{ ResourceTypeV2.NavigationMesh, "Navigation Mesh" },
		{ ResourceTypeV2.TextFile, "Text File" },
		{ ResourceTypeV2.TextFileList, "Text File List" },
		{ ResourceTypeV2.ResourceHandleList, "Resource Handle List" },
		{ ResourceTypeV2.LuaData, "Lua Data" },
		{ ResourceTypeV2.AllocatorInPool, "Allocator in Pool" },
		{ ResourceTypeV2.Ginsu, "Ginsu" },
		{ ResourceTypeV2.Wave, "Wave" },
		{ ResourceTypeV2.WaveContainerTable, "Wave Container Table" },
		{ ResourceTypeV2.GameplayLinkData, "Gameplay Link Data" },
		{ ResourceTypeV2.WaveDictionary, "Wave Dictionary" },
		{ ResourceTypeV2.MicroMonoStream, "Micro Mono Stream" },
		{ ResourceTypeV2.Reverb, "Reverb" },
		{ ResourceTypeV2.ZoneList, "Zone List" },
		{ ResourceTypeV2.WorldPaintMap, "World Paint Map" },
		{ ResourceTypeV2.IceAnimDictionary, "ICE Animation Dictionary" },
		{ ResourceTypeV2.AnimationList, "Animation List" },
		{ ResourceTypeV2.PathAnimation, "Path Animation" },
		{ ResourceTypeV2.AnimSkel, "Animation Skeleton" },
		{ ResourceTypeV2.Animation, "Animation" },
		{ ResourceTypeV2.CgsVertexProgramState, "Vertex Program State (Game)" },
		{ ResourceTypeV2.CgsProgramBuffer, "Vertex Program Buffer (Game)" },
		{ ResourceTypeV2.DeltaDeleted, "Delta Deleted" },
		{ ResourceTypeV2.VehicleList, "Vehicle List" },
		{ ResourceTypeV2.VehicleGraphicsSpec, "Vehicle Graphics" },
		{ ResourceTypeV2.VehiclePhysicsSpec, "Vehicle Physics" },
		{ ResourceTypeV2.WheelList, "Wheel List" },
		{ ResourceTypeV2.WheelGraphicsSpec, "Wheel Graphics" },
		{ ResourceTypeV2.EnvironmentKeyframe, "Environment Keyframe" },
		{ ResourceTypeV2.EnvironmentTimeLine, "Environment Timeline" },
		{ ResourceTypeV2.EnvironmentDictionary, "Environment Dictionary" },
		{ ResourceTypeV2.FlaptFile, "Flapt File" },
		{ ResourceTypeV2.AIData, "AI Data" },
		{ ResourceTypeV2.Language, "Language" },
		{ ResourceTypeV2.TriggerData, "Trigger Data" },
		{ ResourceTypeV2.RoadData, "Road Data" },
		{ ResourceTypeV2.DynamicInstanceList, "Dynamic Instance List" },
		{ ResourceTypeV2.WorldObject, "World Object" },
		{ ResourceTypeV2.ZoneHeader, "Zone Header" },
		{ ResourceTypeV2.VehicleSound, "Vehicle Sound" },
		{ ResourceTypeV2.RoadMapData, "Road Map Data" },
		{ ResourceTypeV2.CharacterSpec, "Character" },
		{ ResourceTypeV2.CharacterList, "Character List" },
		{ ResourceTypeV2.SurfaceSounds, "Surface Sounds" },
		{ ResourceTypeV2.ReverbRoadData, "Reverb Road Data" },
		{ ResourceTypeV2.CameraTake, "Camera Take" },
		{ ResourceTypeV2.CameraTakeList, "Camera Take List" },
		{ ResourceTypeV2.GroundcoverCollection, "Groundcover Collection" },
		{ ResourceTypeV2.ControlMesh, "Control Mesh" },
		{ ResourceTypeV2.CutsceneData, "Cutscene Data" },
		{ ResourceTypeV2.CutsceneList, "Cutscene List" },
		{ ResourceTypeV2.LightInstanceList, "Light Instance List" },
		{ ResourceTypeV2.GroundcoverInstances, "Groundcover Instances" },
		{ ResourceTypeV2.CompoundObject, "Compound Object" },
		{ ResourceTypeV2.CompoundInstanceList, "Compound Instance List" },
		{ ResourceTypeV2.PropObject, "Prop Object" },
		{ ResourceTypeV2.PropInstanceList, "Prop Instance List" },
		{ ResourceTypeV2.ZoneAmbienceList, "Zone Ambience List" },
		{ ResourceTypeV2.BearEffect, "Bear Effect" },
		{ ResourceTypeV2.BearGlobalParameters, "Bear Global Parameters" },
		{ ResourceTypeV2.ConvexHull, "Convex Hull" },
		{ ResourceTypeV2.HSMData, "HSM Data" },
		{ ResourceTypeV2.TrafficGraphicsStub, "Traffic Graphics Stub" },
		{ ResourceTypeV2.TrafficLaneData, "Traffic Lane Data" }
	};
}
